name: Update modified musescore on drive

on:
  push:
    branches:
      - main
    paths:
      - "*.mscz"
  workflow_dispatch:

jobs:
  get-changed-files:
    runs-on: ubuntu-22.04
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
      has_changes: ${{ steps.changed-files.outputs.any_changed }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.mscz

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  process-files:
    needs: get-changed-files
    if: needs.get-changed-files.outputs.has_changes == 'true'
    uses: ./.github/workflows/process_musescore.yml
    with:
      files_to_process: ${{ needs.get-changed-files.outputs.files }}
    secrets:
      GCP_SERVICE_ACCOUNT_KEY_B64: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_B64 }}